DROP TABLE IF EXISTS person cascade;
DROP TABLE IF EXISTS gender;
DROP TABLE IF EXISTS person_group;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS curriculum cascade;
DROP TABLE IF EXISTS college_group cascade;
DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS speciality;
DROP TABLE IF EXISTS faculty cascade;
DROP TABLE IF EXISTS department cascade;
DROP TABLE IF EXISTS employee cascade;
DROP TABLE IF EXISTS employee_position;
DROP TABLE IF EXISTS position_category;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS course cascade;
DROP TABLE IF EXISTS  course_teacher cascade;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS student_mark CASCADE;
DROP TABLE IF EXISTS control_type;
DROP TABLE IF EXISTS day_of_week;
DROP TABLE IF EXISTS course_time;
DROP TABLE IF EXISTS lesson_type;
DROP TABLE IF EXISTS semester;
DROP TABLE IF EXISTS control_point;
